### ISSUE TITLE
Integration with other react project

### ISSUE THREAD

**Issue by jsartre** [tohjustin/coincharts#4]
Hi,
First thanks for this project - really cool! 
Second I'm starting to learn react (really total newb) and to get integrate it with django.

I can get the project to work on its own which is already a good news. 

I am now trying to integrate it with the django-react-teamplate. It seems to be structured differently.
https://github.com/scottwoodall/django-react-template
Any tips on how and where to get started?

Thanks!
J.

**Comment by tohjustin** [comment]
Glad you found the project cool! 😄 

So in [django-react-template](https://github.com/scottwoodall/django-react-template), the project is split into 2 parts:
### 1. `/backend`
  - contains the code for your app's API server (using Django REST framework + Postgres)
  - this server also hosts static files & you have to make sure that the files you want to serve are in the `frontend/build` directory ([hardcoded here](https://github.com/scottwoodall/django-react-template/blob/master/backend/settings/devl.py#L26))
### 2. `/frontend`
  - contains the code for your react app
  - webpack is configured to bundle your frontend app into the `/build` directory

Since **coincharts** is based of [create-react-app](https://github.com/facebookincubator/create-react-app), `npm run build` already bundles our app into a `/build` directory (same as where [django-react-template](https://github.com/scottwoodall/django-react-template) expects it's static files to be located at!) 

So to integrate it, you only have to replace the entire contents of `/frontend` directory with **coinchart**'s code & here's what I might do:
```bash
git clone https://github.com/scottwoodall/django-react-template
cd django-react-template

# remove unwanted code + clone `coincharts` into `/frontend` dir
rm -rf ./frontend
git clone https://github.com/tohjustin/coincharts.git ./frontend
```

**Comment by jsartre** [comment]
Thanks @tohjustin !
